use anyhow::Result;
use log::info;
use std::fs;
use std::path::Path;

use crate::config::strauss_config::StraussConfig;
use crate::types::symbol::SymbolType;
use crate::types::symbols_collection::DiscoveredSymbols;

/// Generate autoload_aliases.php for backward compatibility.
///
/// Port of PHP Aliases
pub fn generate_aliases(
    working_dir: &Path,
    symbols: &DiscoveredSymbols,
    config: &StraussConfig,
) -> Result<()> {
    let vendor_dir = working_dir.join(&config.vendor_directory);
    let composer_dir = vendor_dir.join("composer");

    if !composer_dir.exists() {
        fs::create_dir_all(&composer_dir)?;
    }

    let aliases_content = build_aliases_content(symbols);
    fs::write(
        composer_dir.join("autoload_aliases.php"),
        aliases_content,
    )?;

    info!("Generated aliases file");

    Ok(())
}

fn build_aliases_content(symbols: &DiscoveredSymbols) -> String {
    let mut lines = vec![
        "<?php\n".to_string(),
        "\n".to_string(),
        "// autoload_aliases.php @generated by strauss-rs\n".to_string(),
        "// This file is for development only. Do not include in production.\n".to_string(),
        "\n".to_string(),
    ];

    // Class aliases
    for symbol in symbols.get_all_classes() {
        let repl = symbol.get_replacement();
        if !symbol.do_rename || symbol.original_symbol == repl {
            continue;
        }
        lines.push(format!(
            "class_alias('{}', '{}');\n",
            repl, symbol.original_symbol
        ));
    }

    // Interface aliases
    for symbol in symbols.get_interfaces() {
        let repl = symbol.get_replacement();
        if !symbol.do_rename || symbol.original_symbol == repl {
            continue;
        }
        lines.push(format!(
            "class_alias('{}', '{}');\n",
            repl, symbol.original_symbol
        ));
    }

    lines.join("")
}
