use anyhow::Result;
use log::info;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

use crate::config::strauss_config::StraussConfig;
use crate::config::composer_package::ComposerPackage;
use crate::types::discovered_files::DiscoveredFiles;
use crate::types::symbols_collection::DiscoveredSymbols;

/// Generate Composer-compatible autoloader files in the target directory.
///
/// Port of PHP Autoload/DumpAutoload
pub fn generate_autoloader(
    working_dir: &Path,
    files: &DiscoveredFiles,
    symbols: &DiscoveredSymbols,
    dependencies: &[ComposerPackage],
    config: &StraussConfig,
) -> Result<()> {
    let target_dir = working_dir.join(&config.target_directory);
    let composer_dir = target_dir.join("composer");

    fs::create_dir_all(&composer_dir)?;

    // Generate autoload_classmap.php
    let classmap = generate_classmap(files, symbols, &target_dir)?;
    fs::write(
        composer_dir.join("autoload_classmap.php"),
        classmap,
    )?;

    // Generate autoload_psr4.php
    let psr4 = generate_psr4(dependencies, config)?;
    fs::write(
        composer_dir.join("autoload_psr4.php"),
        psr4,
    )?;

    // Generate autoload_files.php
    let autoload_files = generate_files_autoload(dependencies, config)?;
    fs::write(
        composer_dir.join("autoload_files.php"),
        autoload_files,
    )?;

    // Generate autoload.php entry point
    let suffix = generate_suffix();
    let autoload_php = generate_autoload_php(&suffix);
    fs::write(target_dir.join("autoload.php"), autoload_php)?;

    // Generate autoload_real.php
    let autoload_real = generate_autoload_real(&suffix, config)?;
    fs::write(
        composer_dir.join("autoload_real.php"),
        autoload_real,
    )?;

    // Generate autoload_static.php
    let autoload_static = generate_autoload_static(&suffix)?;
    fs::write(
        composer_dir.join("autoload_static.php"),
        autoload_static,
    )?;

    // Copy ClassLoader.php
    let classloader = include_str!("../data/ClassLoader.php.template");
    fs::write(composer_dir.join("ClassLoader.php"), classloader)?;

    info!("Generated autoloader in {}", target_dir.display());

    Ok(())
}

fn generate_classmap(
    files: &DiscoveredFiles,
    _symbols: &DiscoveredSymbols,
    target_dir: &Path,
) -> Result<String> {
    let mut lines = vec!["<?php\n\n// autoload_classmap.php @generated by strauss-rs\n\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n".to_string()];

    // TODO: Build actual classmap from discovered symbols and file paths

    lines.push(");\n".to_string());
    Ok(lines.join(""))
}

fn generate_psr4(
    dependencies: &[ComposerPackage],
    config: &StraussConfig,
) -> Result<String> {
    let mut lines = vec!["<?php\n\n// autoload_psr4.php @generated by strauss-rs\n\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n".to_string()];

    for pkg in dependencies {
        for (ns, paths) in &pkg.autoload_psr4 {
            let prefixed_ns = if let Some(ref prefix) = config.namespace_prefix {
                format!("{}\\{}", prefix.trim_end_matches('\\'), ns.trim_end_matches('\\'))
            } else {
                ns.clone()
            };

            for path in paths {
                let full_path = format!("{}/{}", pkg.name, path.trim_end_matches('/'));
                lines.push(format!(
                    "    '{}\\\\' => array($vendorDir . '/{}'),\n",
                    prefixed_ns.replace('\\', "\\\\"),
                    full_path,
                ));
            }
        }
    }

    lines.push(");\n".to_string());
    Ok(lines.join(""))
}

fn generate_files_autoload(
    dependencies: &[ComposerPackage],
    _config: &StraussConfig,
) -> Result<String> {
    let mut lines = vec!["<?php\n\n// autoload_files.php @generated by strauss-rs\n\n$vendorDir = dirname(__DIR__);\n$baseDir = dirname($vendorDir);\n\nreturn array(\n".to_string()];

    for pkg in dependencies {
        for file in &pkg.autoload_files {
            let hash = md5::compute(format!("{}/{}", pkg.name, file));
            let full_path = format!("{}/{}", pkg.name, file);
            lines.push(format!(
                "    '{:x}' => $vendorDir . '/{full_path}',\n",
                hash,
            ));
        }
    }

    lines.push(");\n".to_string());
    Ok(lines.join(""))
}

fn generate_suffix() -> String {
    use std::time::SystemTime;
    let seed = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    format!("{:x}", md5::compute(seed.to_string()))
}

fn generate_autoload_php(suffix: &str) -> String {
    format!(
        r#"<?php

// autoload.php @generated by strauss-rs

if (PHP_VERSION_ID < 50600) {{
    if (!headers_sent()) {{
        header('HTTP/1.1 500 Internal Server Error');
    }}
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running ' . PHP_VERSION . ', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.' . PHP_EOL;
    if (!ini_get('display_errors')) {{
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {{
            fwrite(STDERR, $err);
        }} elseif (!headers_sent()) {{
            echo $err;
        }}
    }}
    trigger_error($err, E_USER_ERROR);
}}

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit{suffix}::getLoader();
"#,
        suffix = suffix,
    )
}

fn generate_autoload_real(suffix: &str, _config: &StraussConfig) -> Result<String> {
    Ok(format!(
        r#"<?php

// autoload_real.php @generated by strauss-rs

class ComposerAutoloaderInit{suffix}
{{
    private static $loader;

    public static function loadClassLoader($class)
    {{
        if ('Composer\Autoload\ClassLoader' === $class) {{
            require __DIR__ . '/ClassLoader.php';
        }}
    }}

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {{
        if (null !== self::$loader) {{
            return self::$loader;
        }}

        spl_autoload_register(array('ComposerAutoloaderInit{suffix}', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit{suffix}', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInit{suffix}::getInitializer($loader));

        $loader->register(true);

        $filesToLoad = \Composer\Autoload\ComposerStaticInit{suffix}::$files;
        foreach ($filesToLoad as $fileIdentifier => $file) {{
            composerRequire{suffix}($fileIdentifier, $file);
        }}

        return $loader;
    }}
}}

function composerRequire{suffix}($fileIdentifier, $file)
{{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {{
        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

        require $file;
    }}
}}
"#,
        suffix = suffix,
    ))
}

fn generate_autoload_static(suffix: &str) -> Result<String> {
    Ok(format!(
        r#"<?php

// autoload_static.php @generated by strauss-rs

namespace Composer\Autoload;

class ComposerStaticInit{suffix}
{{
    public static $files = array ();
    public static $prefixLengthsPsr4 = array ();
    public static $prefixDirsPsr4 = array ();
    public static $classMap = array ();

    public static function getInitializer(ClassLoader $loader)
    {{
        return \Closure::bind(function () use ($loader) {{
            $loader->prefixLengthsPsr4 = ComposerStaticInit{suffix}::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit{suffix}::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit{suffix}::$classMap;

        }}, null, ClassLoader::class);
    }}
}}
"#,
        suffix = suffix,
    ))
}
